# Generated by Django 6.0.6 on 2026-06-09 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('_password', models.TextField(db_column='password')),
                ('url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('social', 'Social Media'), ('dev', 'Developer Tools'), ('email', 'Email'), ('finance', 'Finance & Banking'), ('work', 'Work & Productivity'), ('remote', 'Remote Desktop'), ('cloud', 'Cloud Storage'), ('shopping', 'Shopping'), ('streaming', 'Streaming'), ('other', 'Other')], default='other', max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
