# Generated by Django 5.2.14 on 2026-06-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_dataplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='password_logos/'),
        ),
    ]
