# Generated by Django 5.2.14 on 2026-06-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_passwordentry_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
